### ISSUE TITLE
Routing of ibc denom not working.

### ISSUE THREAD

**Issue by arhamchordia** [strangelove-ventures/packet-forward-middleware#7]
@jtieri @jackzampolin 
Steps of replication : 
1. Setup 3 chains (A, B, C).
2. Create channel between A and B and another between B and C.
3. Send tokens from A to C via B though routing.
4. Sending the ibc tokens from C to A fails. (Sending normal tokens from C to A works)

Hermes version : 0.10.0
Packet-forward-middleware version : v1.0.1
Gaia version : 6.0.0

Sending ibc token back from C to B and then from B to A works. 
Also, the logs do not provide sufficient information for the same.

**Comment by jtieri** [comment]
thanks for opening an issue @arhamchordia 

I'm going to create a new demo in a branch on this repo where I will attempt to reproduce this issue locally. Just to be clear you are able to send tokens from A to C, using B as a router, but you are not able to go back from C to A the same way?

**Comment by arhamchordia** [comment]
@jtieri 
Suppose chain A has a token stakeA and chain C has a token stakeC. I am able to send satkeA from A to C and stakeC from C to A.
The problem occurs when I'm trying to send back satkeA back to chain A from chain C through chain B via routing.

**Comment by puneet2019** [comment]
@jtieri I think sending back ibc/Hash tokens is giving some problems, chain originating tokens are moving across using routing.

**Comment by puneet2019** [comment]
@jtieri any updates on this? Were you able to replicate the issue?

**Comment by jtieri** [comment]
> @jtieri any updates on this? Were you able to replicate the issue? We are planning on adding this to Persistence chain, core-1 If you suggest we can hold this off till next release

Sorry for the delay in getting a reply to you! I needed to update the tests I used for using the packet-forward-middleware on my local machine and didn't have the bandwidth until yesterday evening. I'm going to make this my top priority today and get back to you ASAP!

**Comment by arhamchordia** [comment]
Any updates on this issue @jtieri.

**Comment by jtieri** [comment]
@arhamchordia I have had to make some changes around our local testing environment due to some changes and errors introduced in the v6.0.0 release of gaia. 

Unfortunately I haven't gotten everything fully working again so haven't been able to test a fix for the issue described :/

**Comment by arhamchordia** [comment]
Hey @jtieri 
Any updates on this issue?

**Comment by Ehsan-saradar** [comment]
Hi, I encountered the same problem during my testing on `gaia`.
**How to reproduce the problem**

1. Run 3 instances of `gaiad v6.0.3` (in my case i did this with `starport`) and name them A, B, C
2. Create `transfer` channel for each pair (e.g. A-B, A-C, B-C) and start the relayer. 
3. Transfer assets from A to B using the following command
`gaiad tx ibc-transfer transfer transfer channel-0 "B-addr" 1000stake --home ~/.A --node={A-node} --from bob --chain-id A`
4. Transfer the received tokens on B to C through A
`gaiad tx ibc-transfer transfer transfer channel-1 "cosmos16plylpsgxechajltx9yeseqexzdzut9g8vla4k|transfer/channel-1:C-addr" 1000ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9 --home ~/.B --node={B-node} --from bob --chain-id B`

 Now after step 5 if we take a look at relayer log we'll see something like this:
 ```
Relay 1 packets from B => A
Relay 1 acks from A => B
```
Which shows that there's a problem with how router is handling ibc denoms because when you try it with native tokens relayer's output is like this:
```
Relay 1 packets from B => A
Relay 1 packets from A => C
Relay 1 acks from A => B
Relay 1 acks from C => A
```
Starport version : v0.19.2
Packet-forward-middleware version : v1.0.1
Gaia version : 6.0.3

**Comment by jtieri** [comment]
Sorry for the delay!

I've recreated the issue in our test environment and have identified the issue. Working on a patch to fix the issue that should be ready before the theta upgrade on the hub this month.

**Comment by Ehsan-saradar** [comment]
@jtieri Any update on this issue?
